### ISSUE TITLE
Corrupt Saves

### ISSUE THREAD

**Issue by J-Noether** [gbasood/ShatteredEuropeEU4#22]
Hi, I want to preface this with 1) I love the mod, 2) I'm on a mac.

Every time I try to load a saved game, it tells me the save file is corrupted and then partially loads the save. The interesting bit is that the game will manage to load provinces #1-27 (ie most of Scandinavia), with the rest of the world becoming uncolonized land. 

Here's a link to one of my (compressed) [saves](https://www.dropbox.com/s/dmedy7yw0zthk8x/corrupt.eu4?dl=0)

**Comment by taw** [comment]
@J-Noether There were wrong tags in map history files (country names and culture names), which old versions of EU4 handled reasonably, but recently that causes null nonsense and save game corruption in 1.9.x.

All of them should be fixed on github version. If you want to manually fix existing save file, removing all lines with just (and nothing after `=`):

```
add_core=
remove_core=
discovered_by=
```

should solve the crashes. (it will still have a bunch of `noculture` provinces unless you restart the campaign with most recent version, but they shouldn't crash anything)

**Comment by J-Noether** [comment]
Thanks :D
